# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'package'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: 'target/site/jacoco/jacoco.xml'
- task: PublishCucumberReport@1
  inputs:
    jsonDir: 'target/'
    outputPath: 'target/HtmlReports/'
    theme: 'bootstrap'
    reportSuiteAsScenarios: true
    name: 'Cucumber HTML Report for demo'
    title: 'HTML Report'