/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pkgPresentacion;

import java.sql.*;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import pkgNegocio.RenderTabla;
import pkgEntidad.clsECliente;
import pkgNegocio.clsNCliente;

/**
 *
 * @author Acer
 */
public class FrmCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmClienteIn
     */
    DefaultTableModel model=new DefaultTableModel();
    public FrmCliente() {
        initComponents();
        MostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCodbuscar = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLACLIENTE = new javax.swing.JTable();
        btnSalir1 = new javax.swing.JButton();

        btnListar.setBackground(new java.awt.Color(255, 102, 51));
        btnListar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jPanel1.setForeground(new java.awt.Color(204, 204, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("FORMULARIO CLIENTE");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setText("DNI");

        txtdni.setBackground(new java.awt.Color(255, 204, 153));
        txtdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdniActionPerformed(evt);
            }
        });

        txtapellido.setBackground(new java.awt.Color(255, 204, 153));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("APELLIDO");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 204));
        jLabel5.setText("TELEFONO");

        txttelefono.setBackground(new java.awt.Color(255, 204, 153));

        txtnombre.setBackground(new java.awt.Color(255, 204, 153));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("NOMBRE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16)
                        .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2)
                                .addGap(16, 16, 16)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel3)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
        );

        btnSalir.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setText("Busqueda DNI:");

        btnNuevo.setBackground(new java.awt.Color(255, 102, 51));
        btnNuevo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnNuevo.setText("Limpiar");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(255, 102, 51));
        btnGuardar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnGuardar.setText("Agregar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        TABLACLIENTE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TABLACLIENTE.setForeground(new java.awt.Color(102, 102, 255));
        TABLACLIENTE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TABLACLIENTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLACLIENTEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLACLIENTE);

        btnSalir1.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnSalir1.setText("PDF");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtCodbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(247, 247, 247))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnListar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCodbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    public void inicio(){
//        this.setTitle("Botones en JTable");this.setResizable(false);this.setLocationRelativeTo(null);
//    }
    
    public void Limpiar() {
        txtdni.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txttelefono.setText("");
    }
    
    private void MostrarTabla(){
        ResultSet rs;
        clsNCliente objNclie = new clsNCliente();
        DefaultTableModel model = new DefaultTableModel();
        Object[] dato = new Object[6]; // Cambiamos el tipo de dato a Object

        try {
            rs = objNclie.Mtdlistar();
            model.setColumnIdentifiers(new Object[] {"DNI", "NOMBRE","APELLIDO","TELEFONO","Editar", "Eliminar"}); // Agregamos los nombres de columna al modelo
            while (rs.next()) {
                dato[0] = rs.getString("dni");
                dato[1] = rs.getString("nombre");
                dato[2] = rs.getString("apellido");
                dato[3] = rs.getString("telefono");
                dato[4] = new JButton("Editar");
                dato[5] = new JButton("Eliminar");// Agregamos el botón en la última posición
                model.addRow(dato);
            }
            this.TABLACLIENTE.setModel(model);
            this.TABLACLIENTE.setDefaultRenderer(Object.class, new RenderTabla());
            
            //damos altura y ancho a las columnas
            this.TABLACLIENTE.setRowHeight(40);
            
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

    }
    
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

        MostrarTabla();

        // Agrega el ListSelectionListener a la JTable
        TABLACLIENTE.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            // Verificar si la selección aún está cambiando y si hay una fila seleccionada
            if (!e.getValueIsAdjusting() && TABLACLIENTE.getSelectedRow() != -1) {
                // Obtener los valores de la fila seleccionada
                String dni = TABLACLIENTE.getValueAt(TABLACLIENTE.getSelectedRow(), 0).toString();
                String direccion = TABLACLIENTE.getValueAt(TABLACLIENTE.getSelectedRow(), 1).toString();
                String telefono = TABLACLIENTE.getValueAt(TABLACLIENTE.getSelectedRow(), 2).toString();
                String email = TABLACLIENTE.getValueAt(TABLACLIENTE.getSelectedRow(), 3).toString();

                // Asignar los valores a las cajas de texto correspondientes
                txtdni.setText(dni);
                txtnombre.setText(direccion);
                txtapellido.setText(telefono);
                txttelefono.setText(email);
            }
        });
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarActionPerformed

    private void txtdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdniActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        FrmPrincipal frmPrincipal = new FrmPrincipal();
        frmPrincipal.setVisible(true);
        this.dispose(); // Cierra el formulario actual

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed

        txtdni.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txttelefono.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        clsECliente objEcli = new clsECliente();
        clsNCliente objNcli = new clsNCliente();

        String codBuscar = txtCodbuscar.getText().trim(); // Obtener el valor de búsqueda y eliminar espacios en blanco

        // Verificar si el campo de búsqueda está vacío
        if (codBuscar.isEmpty()) {
            MostrarTabla(); // Llama a la función MostrarTabla() para listar todos los datos
        } else {
            // Ejecutar la búsqueda según el código ingresado
            objEcli.setDni(txtdni.getText());
            ResultSet rsc = objNcli.MtdBuscarCodigo(objEcli);
            DefaultTableModel model = (DefaultTableModel) TABLACLIENTE.getModel();
            model.setRowCount(0); // Limpiar el modelo de la tabla

            try {
                if (rsc.next()) {
                    Object[] rowData = new Object[6];
                    rowData[0] = rsc.getString("DNI");
                    rowData[1] = rsc.getString("NOMBRE");
                    rowData[2] = rsc.getString("APELLIDO");
                    rowData[3] = rsc.getString("TELEFONO");
                    rowData[4] = new JButton("Editar");
                    rowData[5] = new JButton("Eliminar");

                    model.addRow(rowData);
                } else {
                    JOptionPane.showMessageDialog(null, "No se encontraron resultados para el código ingresado.");
                }
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        clsECliente objEclie=new clsECliente();
        clsNCliente objNclie=new clsNCliente();

        objEclie.setDni(txtdni.getText());
        objEclie.setNombre(txtnombre.getText());
        objEclie.setApellido(txtapellido.getText());
        objEclie.setTelefono(txttelefono.getText());

        if(objNclie.MtdAgregar(objEclie)){
            JOptionPane.showMessageDialog(null,"Datos Guardados");
            MostrarTabla();
            Limpiar();
        }
        else{
            JOptionPane.showMessageDialog(null,"Datos Erroneos");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void TABLACLIENTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLACLIENTEMouseClicked
        int fila = TABLACLIENTE.getSelectedRow();
        int columna = TABLACLIENTE.getSelectedColumn();

        if (columna == 4) { // Verificar si se hizo clic en la columna del botón "Editar"
            JButton botonEditar = (JButton) TABLACLIENTE.getValueAt(fila, columna);

            // Acciones a realizar cuando se hace clic en el botón "Editar"
            if (botonEditar != null && evt.getClickCount() == 1) {
                String dni = (String) TABLACLIENTE.getValueAt(fila, 0);
                String direccion = (String) TABLACLIENTE.getValueAt(fila, 1);
                String telefono = (String) TABLACLIENTE.getValueAt(fila, 2);
                String email = (String) TABLACLIENTE.getValueAt(fila, 3);

                FrmClienteInternal formulario = new FrmClienteInternal();
                formulario.setDatos(dni,direccion,telefono,email);
                formulario.setVisible(true);
            }
        }
        else if(columna == 5){
            // Verificar si se hizo clic en la columna del botón "Eliminar"
            JButton botonEliminar = (JButton) TABLACLIENTE.getValueAt(fila, columna);

            // Acciones a realizar cuando se hace clic en el botón "Eliminar"
            if (botonEliminar != null && evt.getClickCount() == 1) {
                int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar este registro?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
                if (confirmacion == JOptionPane.YES_OPTION) {
                    String dni = (String) TABLACLIENTE.getValueAt(fila, 0);

                    // Lógica para eliminar el registro de la base de datos
                    clsNCliente objNclie = new clsNCliente();
                    if (objNclie.MtdEliminar(dni)) {
                        DefaultTableModel model = (DefaultTableModel) TABLACLIENTE.getModel();
                        model.removeRow(fila);
                        JOptionPane.showMessageDialog(null, "Registro eliminado correctamente");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al eliminar el registro");
                    }
                }
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_TABLACLIENTEMouseClicked

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        clsECliente objEclie=new clsECliente();
        clsNCliente objNclie=new clsNCliente();

//        objEclie.getDni(txtdni.getText());
//        objEclie.getNombre(txtnombre.getText());
//        objEclie.getApellido(txtapellido.getText());
//        objEclie.getTelefono(txttelefono.getText());

//        if(objNclie.pdfClientes(objEclie)){
//            JOptionPane.showMessageDialog(null,"Datos Guardados");
//            MostrarTabla();
//            Limpiar();
//        }
//        else{
//            JOptionPane.showMessageDialog(null,"Datos Erroneos");
//        }
    }//GEN-LAST:event_btnSalir1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABLACLIENTE;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodbuscar;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
