/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pkgPresentacion;

/**
 *
 * @author Acer
 */

import java.sql.*;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import pkgNegocio.RenderTabla;
import pkgEntidad.clsECargo;
import pkgNegocio.clsNCargo;

public class FrmCargo extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCargoIn
     */
    DefaultTableModel model=new DefaultTableModel();
    public FrmCargo() {
        initComponents();
        MostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLALISTA = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCodbuscar = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();

        btnBuscar.setBackground(new java.awt.Color(0, 0, 255));
        btnBuscar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(255, 0, 51));
        btnNuevo.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Limpiar");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 0, 255));
        btnSalir.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtDescripcion.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Descripcion:");

        btnGuardar.setBackground(new java.awt.Color(255, 0, 51));
        btnGuardar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Agregar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnListar.setBackground(new java.awt.Color(255, 0, 51));
        btnListar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("FORMULARIO CARGO");

        TABLALISTA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CODIGO", "DESCRIPCION"
            }
        ));
        TABLALISTA.setName(""); // NOI18N
        TABLALISTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLALISTAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLALISTA);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Busqueda Codigo:");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Codigo:");

        txtCodigo.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigo)
                                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(btnListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCodbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Limpiar() {
        txtCodigo.setText("");
        txtDescripcion.setText("");
    }
    
    private void MostrarTabla(){
        ResultSet rs;
        clsNCargo objNcarg = new clsNCargo();
        DefaultTableModel model = new DefaultTableModel();
        Object[] dato = new Object[4]; // Cambiamos el tipo de dato a Object

        try {
            rs = objNcarg.Mtdlistar();
            model.setColumnIdentifiers(new Object[] {"ID", "NOMBRE","Editar", "Eliminar"}); // Agregamos los nombres de columna al modelo
            while (rs.next()) {
                dato[0] = rs.getString("id");
                dato[1] = rs.getString("nombre");
                dato[2] = new JButton("Editar");
                dato[3] = new JButton("Eliminar");// Agregamos el botón en la última posición
                model.addRow(dato);
            }
            this.TABLALISTA.setModel(model);
            this.TABLALISTA.setDefaultRenderer(Object.class, new RenderTabla());
            
            //damos altura y ancho a las columnas
            this.TABLALISTA.setRowHeight(40);
            
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

        }
    
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        clsECargo objEca = new clsECargo();
        clsNCargo objNca = new clsNCargo();

        String codBuscar = txtCodbuscar.getText().trim(); // Obtener el valor de búsqueda y eliminar espacios en blanco

        // Verificar si el campo de búsqueda está vacío
        if (codBuscar.isEmpty()) {
            MostrarTabla(); // Llama a la función MostrarTabla() para listar todos los datos
        } else {
            // Ejecutar la búsqueda según el código ingresado
            objEca.setId(Integer.parseInt(codBuscar));
            ResultSet rsc = objNca.MtdBuscarCodigo(objEca);
            DefaultTableModel model = (DefaultTableModel) TABLALISTA.getModel();
            model.setRowCount(0); // Limpiar el modelo de la tabla

            try {
                if (rsc.next()) {
                    Object[] rowData = new Object[4];
                    rowData[0] = rsc.getString("ID");
                    rowData[1] = rsc.getString("NOMBRE");
                    rowData[2] = new JButton("Editar");
                    rowData[3] = new JButton("Eliminar");

                    model.addRow(rowData);
                } else {
                    JOptionPane.showMessageDialog(null, "No se encontraron resultados para el código ingresado.");
                }
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        txtCodigo.setText("");
        txtDescripcion.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        FrmPrincipal frmPrincipal = new FrmPrincipal();
        frmPrincipal.setVisible(true);
        this.dispose(); // Cierra el formulario actual

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        clsECargo objEcar=new clsECargo();
        clsNCargo objNcar=new clsNCargo();

        objEcar.setId(Integer.parseInt(txtCodigo.getText()));
        objEcar.setNombre(txtDescripcion.getText());

        if(objNcar.MtdAgregar(objEcar)){
            JOptionPane.showMessageDialog(null,"Datos Guardados");
            MostrarTabla();
            Limpiar();
        }
        else{
            JOptionPane.showMessageDialog(null,"Datos Erroneos");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

        MostrarTabla();

        // Agrega el ListSelectionListener a la JTable
        TABLALISTA.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // Verificar si la selección aún está cambiando y si hay una fila seleccionada
                if (!e.getValueIsAdjusting() && TABLALISTA.getSelectedRow() != -1) {
                    // Obtener los valores de la fila seleccionada
                    String id = TABLALISTA.getValueAt(TABLALISTA.getSelectedRow(), 0).toString();
                    String nombre = TABLALISTA.getValueAt(TABLALISTA.getSelectedRow(), 1).toString();

                    // Asignar los valores a las cajas de texto correspondientes
                    txtCodigo.setText(id);
                    txtDescripcion.setText(nombre);

                }
            }
        });

    }//GEN-LAST:event_btnListarActionPerformed

    private void TABLALISTAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLALISTAMouseClicked

        int fila = TABLALISTA.getSelectedRow();
        int columna = TABLALISTA.getSelectedColumn();

        if (columna == 2) { // Verificar si se hizo clic en la columna del botón "Editar"
            JButton botonEditar = (JButton) TABLALISTA.getValueAt(fila, columna);

            // Acciones a realizar cuando se hace clic en el botón "Editar"
            if (botonEditar != null && evt.getClickCount() == 1) {
                String id = (String) TABLALISTA.getValueAt(fila, 0);
                String nombre = (String) TABLALISTA.getValueAt(fila, 1);

                FrmCargoInternal formulario = new FrmCargoInternal();
                formulario.setDatos(id,nombre);
                formulario.setVisible(true);
            }
        }
        else if(columna == 3){
            // Verificar si se hizo clic en la columna del botón "Eliminar"
            JButton botonEliminar = (JButton) TABLALISTA.getValueAt(fila, columna);

            // Acciones a realizar cuando se hace clic en el botón "Eliminar"
            if (botonEliminar != null && evt.getClickCount() == 1) {
                int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar este registro?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
                if (confirmacion == JOptionPane.YES_OPTION) {
                    String dni = (String) TABLALISTA.getValueAt(fila, 0);

                    // Lógica para eliminar el registro de la base de datos
                    clsNCargo objNcar = new clsNCargo();
                    if (objNcar.MtdEliminar(dni)) {
                        DefaultTableModel model = (DefaultTableModel) TABLALISTA.getModel();
                        model.removeRow(fila);
                        JOptionPane.showMessageDialog(null, "Registro eliminado correctamente");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error al eliminar el registro");
                    }
                }
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_TABLALISTAMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABLALISTA;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodbuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
