/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package pkgPresentacion;

/**
 *
 * @author Acer
 */

import java.awt.Component;
import java.awt.Image;
import pkgEntidad.clsEHabitaciones;
import pkgNegocio.clsNHabitaciones;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import pkgNegocio.RenderTabla;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
public class FrmInternalListaHab extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmInternalListaHab
     */
    
    public DefaultTableModel modelo;
    public static int seleccion;
    public static String inmcod;
    public static String codper;
    public static String Direccion;
    public static String NroHa;
    public static String Ciudad;
    public static String Descripcion;
    public static String Categoria;
    public static String Precio;
    public static JLabel foto;
    
    public FrmInternalListaHab() {
        initComponents();
        MostrarTabla();
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbhabitaciones = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        txtdnicli = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();

        tbhabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbhabitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbhabitacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbhabitaciones);

        btnListar.setBackground(new java.awt.Color(255, 0, 51));
        btnListar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 903, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtdnicli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdnicli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    void MostrarTabla()
    {
        tbhabitaciones.setDefaultRenderer(Object.class,new RenderTabla());   
        modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("DNI CLIENTE");
        modelo.addColumn("NUMERO");
        modelo.addColumn("TIPO");
        modelo.addColumn("PRECIO");
        modelo.addColumn("ESTADO");
        modelo.addColumn("FOTO");
        modelo.addColumn("ACCIONES");
        clsNHabitaciones objNhab = new clsNHabitaciones();
        JButton boton1 = new JButton("Alquilar");

        Object[] datos = new Object[8];
        for (clsEHabitaciones objEhab : objNhab.MtdListar()) {
            datos[0] = String.valueOf(objEhab.getId());
            datos[1] = String.valueOf(objEhab.getFkdnicli());
            datos[2] = String.valueOf(objEhab.getNumero());
            datos[3] = objEhab.getTipo();
            datos[4] = String.valueOf(objEhab.getPrecio());
            datos[5] = objEhab.getEstado();

            try {
                byte[] bi = objEhab.getFoto();
                BufferedImage image = null;
                InputStream in = new ByteArrayInputStream(bi);
                image = ImageIO.read(in);
                ImageIcon imgi = new ImageIcon(image.getScaledInstance(120, 120, 0));
                datos[6] = imgi;
            } catch (Exception ex) {
                datos[6] = null;
            }

            datos[7] = boton1;
            modelo.addRow(datos);
        }

        this.tbhabitaciones.setModel(modelo);
        tbhabitaciones.setRowHeight(100);
        tbhabitaciones.getColumnModel().getColumn(0).setMaxWidth(80);
        tbhabitaciones.getColumnModel().getColumn(0).setMinWidth(80);
        tbhabitaciones.getColumnModel().getColumn(0).setPreferredWidth(80);
        tbhabitaciones.getColumnModel().getColumn(1).setMaxWidth(100);
        tbhabitaciones.getColumnModel().getColumn(1).setMinWidth(100);
        tbhabitaciones.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbhabitaciones.getColumnModel().getColumn(2).setMaxWidth(80);
        tbhabitaciones.getColumnModel().getColumn(2).setMinWidth(80);
        tbhabitaciones.getColumnModel().getColumn(2).setPreferredWidth(80);
        tbhabitaciones.getColumnModel().getColumn(3).setMaxWidth(100);
        tbhabitaciones.getColumnModel().getColumn(3).setMinWidth(100);
        tbhabitaciones.getColumnModel().getColumn(3).setPreferredWidth(100);
        tbhabitaciones.getColumnModel().getColumn(4).setMaxWidth(130);
        tbhabitaciones.getColumnModel().getColumn(4).setMinWidth(130);
        tbhabitaciones.getColumnModel().getColumn(4).setPreferredWidth(130);
        tbhabitaciones.getColumnModel().getColumn(5).setMaxWidth(170);
        tbhabitaciones.getColumnModel().getColumn(5).setMinWidth(170);
        tbhabitaciones.getColumnModel().getColumn(5).setPreferredWidth(170);
        tbhabitaciones.getColumnModel().getColumn(6).setMaxWidth(130);
        tbhabitaciones.getColumnModel().getColumn(6).setMinWidth(130);
        tbhabitaciones.getColumnModel().getColumn(6).setPreferredWidth(130);
        tbhabitaciones.getColumnModel().getColumn(7).setMaxWidth(130);
        tbhabitaciones.getColumnModel().getColumn(7).setMinWidth(130);
        tbhabitaciones.getColumnModel().getColumn(7).setPreferredWidth(130);

        // Crear un renderizador personalizado para la columna de la imagen
        tbhabitaciones.getColumnModel().getColumn(6).setCellRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = new JLabel();
                if (value instanceof ImageIcon) {
                    ImageIcon icon = (ImageIcon) value;
                    label.setIcon(icon);
                } else {
                    label.setText("No imagen");
                }
                return label;
            }
        });
    }
    
    private void tbhabitacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbhabitacionesMouseClicked
        
        int fila = tbhabitaciones.getSelectedRow();
        int columna = tbhabitaciones.getSelectedColumn();

        if (columna == 7) { // Verificar si se hizo clic en la columna del botón "Editar"
            JButton botonEditar = (JButton) tbhabitaciones.getValueAt(fila, columna);

            // Acciones a realizar cuando se hace clic en el botón "Editar"
            if (botonEditar != null && evt.getClickCount() == 1) {
                String id = (String) tbhabitaciones.getValueAt(fila, 0);
                String fkdnicli = (String) tbhabitaciones.getValueAt(fila, 1);
                String numero = (String) tbhabitaciones.getValueAt(fila, 2);
                String tipo = (String) tbhabitaciones.getValueAt(fila, 3);
                String precio = (String) tbhabitaciones.getValueAt(fila, 4);
                String estado = (String) tbhabitaciones.getValueAt(fila, 5);

                int idInt = Integer.parseInt(id);
                double precioDouble = Double.parseDouble(precio);

                FrmAlquilerHab formulario = new FrmAlquilerHab();
                formulario.setDatos(idInt, fkdnicli, numero, tipo, precioDouble, estado);
                formulario.setVisible(true);

            }
        }
//        else if(columna == 3){
//            // Verificar si se hizo clic en la columna del botón "Eliminar"
//            JButton botonEliminar = (JButton) tbhabitaciones.getValueAt(fila, columna);
//
//            // Acciones a realizar cuando se hace clic en el botón "Eliminar"
//            if (botonEliminar != null && evt.getClickCount() == 1) {
//                int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de eliminar este registro?", "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
//                if (confirmacion == JOptionPane.YES_OPTION) {
//                    String dni = (String) tbhabitaciones.getValueAt(fila, 0);
//
//                    // Lógica para eliminar el registro de la base de datos
//                    clsNCargo objNcar = new clsNCargo();
//                    if (objNcar.MtdEliminar(dni)) {
//                        DefaultTableModel model = (DefaultTableModel) tbhabitaciones.getModel();
//                        model.removeRow(fila);
//                        JOptionPane.showMessageDialog(null, "Registro eliminado correctamente");
//                    } else {
//                        JOptionPane.showMessageDialog(null, "Error al eliminar el registro");
//                    }
//                }
//            }
//        }
        
    }//GEN-LAST:event_tbhabitacionesMouseClicked

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed

        MostrarTabla();

        // Agrega el ListSelectionListener a la JTable
        tbhabitaciones.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                // Verificar si la selección aún está cambiando y si hay una fila seleccionada
                if (!e.getValueIsAdjusting() && tbhabitaciones.getSelectedRow() != -1) {
                    // Obtener los valores de la fila seleccionada
                    String id = tbhabitaciones.getValueAt(tbhabitaciones.getSelectedRow(), 0).toString();
                    String fkdnicli = tbhabitaciones.getValueAt(tbhabitaciones.getSelectedRow(), 1).toString();
                    String numero = tbhabitaciones.getValueAt(tbhabitaciones.getSelectedRow(), 2).toString();
                    String tipo = tbhabitaciones.getValueAt(tbhabitaciones.getSelectedRow(), 3).toString();
                    String precio = tbhabitaciones.getValueAt(tbhabitaciones.getSelectedRow(), 4).toString();
                    String estado = tbhabitaciones.getValueAt(tbhabitaciones.getSelectedRow(), 5).toString();

                    // Asignar los valores a las cajas de texto correspondientes
                    txtid.setText(id);
                    txttipo.setText(fkdnicli);
                    txtnumero.setText(numero);
                    txttipo.setText(tipo);
                    txtprecio.setText(precio);
                    txtdnicli.setText(estado);

                }
            }
        });
    }//GEN-LAST:event_btnListarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbhabitaciones;
    private javax.swing.JTextField txtdnicli;
    private javax.swing.JTextField txtestado;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables
}
